package com.github.easy30.vue4j;

import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Vue 单文件组件转换器 - 将 .vue 文件转换为浏览器可用的 JS 文件
 */
public class VueToJs {

    // 移除了用于匹配 template 和 script 标签的正则表达式，改用 jsoup 解析
    //private static final Pattern TEMPLATE_PATTERN = Pattern.compile("<template\\b[^>]*>([\\s\\S]*)</template>", Pattern.DOTALL);
    //private static final Pattern SCRIPT_PATTERN = Pattern.compile( "<script\\b[^>]*>([\\s\\S]*?)</script>", Pattern.DOTALL);
    //private static final Pattern NAME_PATTERN = Pattern.compile("name:\\s*['"](\\w+)['"]");
    private static final Pattern EXPORT_DEFAULT_PATTERN = Pattern.compile("export\\s+default\\s+(\\{)", Pattern.DOTALL);

    /**
     * 将 .vue 文件转换为 .js 文件并保存到指定路径
     * 
     * @param vuePath .vue 源文件的完整路径
     * @param jsPath 转换后 .js 文件的目标保存路径
     * @param charset 文件编码字符集，如 "UTF-8"
     * @throws IOException 当读取源文件或写入目标文件失败时抛出
     */
    public static void convertVueToJs(Path vuePath, Path jsPath, String charset) throws IOException {
        String vueContent = new String(Files.readAllBytes(vuePath), charset);
        String jsContent = convertVueToJs(vueContent, vuePath.getFileName().toString());
        Files.write(jsPath, jsContent.getBytes(charset));
    }

    /**
     * 将 .vue 文件内容转换为 .js 文件内容（字符串形式）
     * 
     * @param vueContent .vue 文件的原始内容
     * @param fileName 文件名（用于提取组件名，当 script 中未定义 name 时使用）
     * @return 转换后的 JavaScript 代码字符串
     * @throws IOException 当解析 Vue 文件格式错误时抛出（缺少 template 或 script 标签）
     */
    public static String convertVueToJs(String vueContent, String fileName) throws IOException {
        Document doc = Jsoup.parse(vueContent);
        String template = extractTemplate(doc,vueContent);
        String scriptContent = extractScript(doc,vueContent);
        //String componentName = extractComponentName(scriptContent, fileName);
        return generateJsContent(null, scriptContent, template);
    }

    /**
     * 从 Vue 文件中提取 template 标签内的内容
     * 
     * @param vueContent Vue 文件的完整内容
     * @return 提取的模板 HTML 字符串（已去除首尾空白）
     * @throws IOException 当文件中缺少 template 标签时抛出
     */
    private static String extractTemplate( Document doc ,String vueContent) throws IOException {

        Element templateElement = doc.selectFirst("template");
        if (templateElement == null) {
            throw new IOException("Invalid Vue file: missing <template>");
        }
        return templateElement.html().trim();
    }

    /**
     * 从 Vue 文件中提取 script 标签内的内容
     * 
     * @param vueContent Vue 文件的完整内容
     * @return 提取的 JavaScript 代码字符串（已去除首尾空白）
     * @throws IOException 当文件中缺少 script 标签时抛出
     */
    private static String extractScript( Document doc ,String vueContent) throws IOException {
        Element scriptElement = doc.selectFirst("script");
        if (scriptElement == null) {
            throw new IOException("Invalid Vue file: missing <script>");
        }
        return scriptElement.html().trim();
    }

    /**
     * 从 script 内容中提取组件名称，如果未定义则根据文件名生成
     * 
     * @param scriptContent Vue 组件的 script 部分内容
     * @param fileName 原始文件名（不含路径）
     * @return 组件名称（首字母大写）
     */
//    private static String extractComponentName(String scriptContent, String fileName) {
//        Matcher matcher = NAME_PATTERN.matcher(scriptContent);
//        if (matcher.find()) {
//            return matcher.group(1);
//        }
//        String baseName = fileName.replace(".vue", "");
//        return capitalizeFirstLetter(baseName);
//    }

    /**
     * 将字符串的首字母转换为大写
     * 
     * @param str 待处理的字符串
     * @return 首字母大写后的字符串；如果输入为 null 或空字符串则原样返回
     */
    private static String capitalizeFirstLetter(String str) {
        if (str == null || str.isEmpty()) {
            return str;
        }
        return Character.toUpperCase(str.charAt(0)) + str.substring(1);
    }

    /**
     * 生成最终的 JavaScript 文件内容，包含注释头和导出语句
     * 
     * @param componentName 组件名称
     * @param scriptContent 处理后的 script 内容
     * @param template 模板 HTML 字符串
     * @return 完整的 JavaScript 代码（可直接在浏览器中使用）
     */
    private static String generateJsContent(String componentName, String scriptContent, String template) {
        StringBuilder jsContent = new StringBuilder();
        //jsContent.append("// ").append(componentName).append(".js - Auto-generated from ").append(componentName).append(".vue\n");
        //jsContent.append("// DO NOT EDIT THIS FILE DIRECTLY\n\n");
        //jsContent.append("export default ");

        String processedScript = processScript(scriptContent, template);
        jsContent.append(processedScript).append(";\n");

        return jsContent.toString();
    }

    /**
     * 处理 script 内容，移除 export default 关键字并添加 template 属性
     * 
     * @param scriptContent Vue 组件的 script 内容
     * @param template 模板 HTML 字符串
     * @return 处理后的对象字面量字符串（不含 export default 前缀）
     */
    private static String processScript(String scriptContent, String template) {
        // 检查是否已经有 template
//        if (scriptContent.contains("template:")) {
//            return scriptContent;
//        }

        // 使用正则匹配 export default {
        Matcher matcher = EXPORT_DEFAULT_PATTERN.matcher(scriptContent);
        if (!matcher.find()) {
            return scriptContent;
        }

        // 找到 { 的位置
        int bracePos = matcher.start(1);

        // 在 { 后面插入 template:
        StringBuilder result = new StringBuilder(scriptContent);
        result.insert(bracePos + 1, "\n    template: `" + escapeTemplate(template) + "`,");

        return result.toString();
    }


    /**
     * 转义模板字符串中的特殊字符，使其可以安全地嵌入到 JavaScript 模板字符串中
     * 
     * @param template 原始模板字符串
     * @return 转义后的字符串（反斜杠、反引号、${占位符} 都会被转义）
     */
    private static String escapeTemplate(String template) {
        return template
                .replace("\\", "\\\\")
                .replace("`", "\\`")
                .replace("${", "\\${");
    }


}
